version: 2
jobs:
  build:
    docker:
      - image: julia:1.1.0
    steps:
      # we need to install git before checkout our code
      - run:
          name: install dependencies
          command: |
            apt update && apt install -y git python3 python3-dev wget
            wget https://bootstrap.pypa.io/get-pip.py && python3 get-pip.py && rm get-pip.py
      - checkout
      - run:
          name: install python dependencies
          command: |
            pip3 install --upgrade pip
            pip3 install -r requirements.txt
      - run:
          name: test
          command: |
            julia --project -e 'ENV["PYTHON"]=Sys.which("python3");\
                      using Pkg;\
                      pkg"activate .";\
                      pkg"add Coverage"
                      pkg"test"; \
                      Codecov.submit(process_folder())'

